apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-airconnect
  labels:
    app: airconnect
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: airconnect
  template:
    metadata:
      labels:
        app: airconnect
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
